import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styled from 'styled-components';

import {getAllFilesMetadata} from '../lib/mdx';

type Props = {
  posts?: Array<Post>
}

type Post = {
  slug: string,
  title: string,
  date?: string,
  content: string
}

const Home: NextPage<Props> = ({posts}) => {
  return (
    <div>
      <Head>
        <title>Serdev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <p>Ultimos articulos</p>
        <div>
         {posts?.map((post) => (
            <Link 
            key={post.slug} href={`/${post.slug}`}>
              <a>
                <h2>{post.title}</h2>
                <p>{post.content}</p>              
              </a>
          </Link>
         ))}
        </div>
      </main>
    </div>
  )
}


export async function getStaticProps() {
  const posts = await getAllFilesMetadata();
  console.log(posts)
  return {
    props: { posts } 
  }
}

export default Home
