import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styled from 'styled-components';

import {getAllFilesMetadata} from '../lib/mdx';

type Props = {
  posts?: Array<Post>
}

type Post = {
  slug: string,
  title: string,
  date?: string,
  content: string,
  descripcion?: string,
}

const StyledMain = styled.main`
  max-width: 1000px;
  display: flex;
  flex-direction: column;
  padding: 0 50px;
  height: 100vh;
  overflow:hidden;

  flex-direction: column;
  .contenedor{
    width:100%;
    margin:150px 0 0 150px;
    color:white;
  }

  .box{
    width:100px;
  }
  .posts{
    margin-top:50px;
  }


  @media screen and (min-width: 1025px) {
    
  }
  @media screen and (min-width: 1280px) {

  }
`;



const Home: NextPage<Props> = ({posts}) => {
  console.log(posts);
  return (
    <div>
      <Head>
        <title>Serdev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledMain>
      <main>
        <div className="contenedor">
        <h3>Últimos articulos</h3>
        <div className="posts">
         {posts?.map((post) => (
            <Link 
            key={post.slug} href={`/${post.slug}`}>
              <a className="box">
                <h2>{post.title}</h2>
                <p>{post.descripcion}</p>
                           
              </a>
          </Link>
         ))}
        </div>
       </div>
      </main>
      </StyledMain>
    </div>
  )
}


export async function getStaticProps() {
  const posts = await getAllFilesMetadata();
  console.log(posts)
  return {
    props: { posts } 
  }
}

export default Home
