import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styled from 'styled-components';



const Proyectos: NextPage = () => {
    //const tag = posts.tags.split(',');
     // console.log(posts);
      return (
        <>
          <Head>
            <title>Proyectos</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
         
          <main>
            
          </main>
        </>
      )
    }
    
    
    
    export default Proyectos
    